### ISSUE TITLE
Search menu on schedule should filter list of event cards

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/mgs2017#59] opened 2017-01-17 15:28 UTC
I started trying to figure it out, but again, over my head...

**Comment by webmasterkai** [comment] 2017-01-18 23:49
We need to establish what fields are being searched

**Comment by bjornmeansbear** [comment] 2017-01-19 00:11
I started trying to document this in #33

**Comment by webmasterkai** [comment] 2017-01-19 00:12
Duplicate of #33

**Closed as completed by webmasterkai** 2017-01-19 00:12 UTC
